version: '3'

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.6.1-community
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    restart: always
  sonarqube-db:
    image: postgres:12
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data