version: '3'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    restart: always
    environment:
      - AUTH_TYPE=OAUTH2
      - AUTH_OAUTH2_CLIENT_AUTH0_CLIENTID=xxxx
      - AUTH_OAUTH2_CLIENT_AUTH0_CLIENTSECRET=xxxx
      - AUTH_OAUTH2_CLIENT_AUTH0_SCOPE=openid,email,name,offline_access,profile
      - AUTH_OAUTH2_CLIENT_AUTH0_ISSUER_URI=https://kafka-ui.sso.xxxx.com/oidc
      - AUTH_OAUTH2_CLIENT_AUTH0_PROVIDER=authing
      - AUTH_OAUTH2_CLIENT_AUTH0_USERNAMEATTRIBUTE=email
      - SERVER_FORWARDHEADERSSTRATEGY=native

      - KAFKA_CLUSTERS_0_NAME=dev
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=127.0.0.1:9091,127.0.0.1:9092,127.0.0.1:9093
      - KAFKA_CLUSTERS_0_READONLY=false

      - KAFKA_CLUSTERS_1_NAME=test
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=127.0.0.1:9091,127.0.0.1:9092,127.0.0.1:9093
      - KAFKA_CLUSTERS_1_READONLY=true
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime