version: "3.7"
services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.4.3.25-alpine
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
