version: "3"
services:
  sqlpad:
    container_name: sqlpad 
    image: sqlpad/sqlpad:latest
    environment:
    - SQLPAD_ADMIN=admin
    - SQLPAD_ADMIN_PASSWORD=admin
    ports:
    - "3001:3000"
    restart: always
    volumes:
      - ./sqlpad-data:/var/lib/sqlpad