version: "3.1"

services:

  logicaldoc:
    depends_on:
      - mysql-ld
    command: ["./wait-for-it.sh", "mysql-ld:3306", "-t", "30", "--", "/opt/logicaldoc/start-logicaldoc.sh", "run"]
    image: logicaldoc/logicaldoc-ce
    ports:
      - 8080:8080
    environment:
      - LDOC_MEMORY=2000

  mysql-ld: 
    image: mysql:8.0
    command: --default-authentication-pluve_password
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=logicaldoc
      - MYSQL_USER=ldoc
      - MYSQL_PASSWORD=changeme
      
      
      
# docker run --name openkm-ce -p 8080:8080 openkm/openkm-ce
# https://github.com/logicaldoc/community