permission:
  - name: log
    path: /query
    api:
      - name: 获取日志列表
        method: GET
        path: /api/query/logs
      - name: 获取日志图表
        method: GET
        path: /api/query/charts
      - name: 获取日志tables
        method: GET
        path: /api/query/tables
  - name: alarm
    path: /alarm
    children:
      - name: rules
        path: /alarm/rules
      - name: environment
        path: /alarm/environment
      - name: notifications
        path: /alarm/notifications
  - name: configure
    path: /configure
  - name: bigdata
    path: /bigdata
  - name: systemSettings
    path: /sys
    children:
      - path: /sys/instances
        name: database
        api:
        - name: 查询数据库连接
          method: GET
          path: /api/sys/instances
        - name: 新增数据库连接
          method: POST
          path: /api/sys/instances
        - name: 更新数据库连接
          method: PATCH
          path: /api/sys/instances/:id
        - name: 删除数据库连接
          method: DELETE
          path: /api/sys/instances/:id
      - path: /sys/clusters
        name: cluster
        api:
        - name: 查询数据库连接
          method: GET
          path: /api/v1/sys/clusters
        - name: 新增数据库连接
          method: POST
          path: /api/v1/sys/clusters
        - name: 更新数据库连接
          method: PATCH
          path: /api/v1/sys/clusters/:id
        - name: 删除数据库连接
          method: DELETE
          path: /api/v1/sys/clusters/:id
      - name: events
        path: /sys/events
      - name: pms
        path: /sys/pms
        api:
          - path: /api/v1/pms/commonInfo
            name: 获取权限常量信息
            method: GET
          - path: /api/v1/pms/defaultRole/list
            name: 全局默认角色列表
            method: GET
          - path: /api/v1/pms/app/:id/role/grant
            name: 获取应用的角色授权信息
            method: GET
          - path: /api/v1/pms/app/:id/role/grant
            name: 获取应用的角色授权信息
            method: PUT
          - path: /api/v1/pms/role
            name: 获取权限角色列表
            method: GET
          - path: /api/v1/pms/role/:id
            name: 获取指定权限角色
            method: GET
          - path: /api/v1/pms/role
            name: 创建权限角色
            method: POST
          - path: /api/v1/pms/role/:id
            name: 更新指定权限角色
            method: PUT
          - path: /api/v1/pms/role/:id
            name: 删除权限角色
            method: DELETE
          - path: /api/v1/pms/root/uids
            name: 获取超级管理员用户id
            method: GET
          - path: /api/v1/pms/root/grant
            name: 授权超级管理员
            method: POST
          - path: /api/v1/pms/check
            name: 查询权限
            method: POST
      - name: user
        path: /sys/user
