version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32-debian
    volumes:
      - "./mysql_data:/var/lib/mysql"
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: irH2YmjsoJPzpNgC