version: "3"

services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2022-02-07T08-17-33Z
    ports:
      - 9000:9000 # api 端口
      - 9001:9001 # 控制台端口
    environment:
      MINIO_ROOT_USER: admin    #管理后台用户名
      MINIO_ROOT_PASSWORD: admin123 #管理后台密码，最小8个字符
    volumes:
      - ./minio_data:/data       #映射当前目录下的data目录至容器内/data目录
      - ./minio_config:/root/.minio/  #映射配置目录
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3