version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-02-07T08-17-33Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    container_name: minio1
    volumes:
      - ./minio-data1-1:/data1
      - ./minio-data1-2:/data2
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime

  minio2:
    <<: *minio-common
    container_name: minio2
    volumes:
      - ./minio-data2-1:/data1
      - ./minio-data2-2:/data2
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime

  minio3:
    <<: *minio-common
    container_name: minio3
    volumes:
      - ./minio-data3-1:/data1
      - ./minio-data3-2:/data2

  minio4:
    <<: *minio-common
    container_name: minio4
    volumes:
      - ./minio-data4-1:/data1
      - ./minio-data4-2:/data2
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime

  minio-gateway:
    container_name: minio-gateway
    image: nginx:1.19.2-alpine
    volumes:
      - ./cluster-config/nginx-gateway.conf:/etc/nginx/nginx.conf:ro
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4