version: "3"
services:
  goproxy:
    container_name: goproxy
    image: goproxy/goproxy:latest
    command: "-listen=0.0.0.0:80 -cacheDir=/ext -proxy https://goproxy.cn -exclude 'gitlab.test.com'"
    ports:
      - "80:8081"
    restart: always
    volumes:
      - ./goproxy-data:/ext
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime